name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          extra_system_packages: "perl-file-which"

      - name: Commit pdf
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add main.pdf
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git commit -m 'Update main.pdf'
            git push
          fi